name: test

defaults:
  run:
    shell: bash

env:
  TERM: xterm-256color

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: run dockerized test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci
          outputs: type=local,dest=/tmp/output/
      - name: print dockerized test output
        run: scripts/cat-all.sh /tmp/output/ --github
