name: test

defaults:
  run:
    shell: bash

env:
  TERM: xterm-256color

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: docker ci-test
        uses: docker/build-push-action@v3
        with:
          context: .
          file: node/apps/client-ui/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci
          outputs: type=local,dest=/tmp/output/
      - name: print /output/
        run: scripts/cat-all.sh /tmp/output/ --github
